<?php
set_time_limit(240);
require 'Fonctions.php';

$Page           = isset($_POST['Page']) ? $_POST['Page'] : 1;                       // Page du blog
$NumArt         = isset($_POST['NumArt']) ? $_POST['NumArt'] : 0;                   // N° d'article dans la page de 0 a 4
$NumCom         = isset($_POST['NumCom']) ? $_POST['NumCom'] : 1;                   // N° de page de comentaire de 1 a ...
$Domaine        = isset($_POST['Domaine']) ? $_POST['Domaine'] : '';                  
$AncienBlog     = isset($_POST['AncienBlog']) ? $_POST['AncienBlog'] : 'http://' . trim($_POST['NomBlog']) . '.' . $Domaine;
$NouveauBlog    = isset($_POST['NouveauBlog']) ? $_POST['NouveauBlog'] : '';
$VotreNom       = isset($_POST['VotreNom']) ? $_POST['VotreNom'] : '';
$VotreEmail     = isset($_POST['VotreEmail']) ? $_POST['VotreEmail'] : '';
$FichierNum     = isset($_POST['FichierNum']) ? $_POST['FichierNum'] : 1;
$ChangeFichier  = isset($_POST['ChangeFichier']) ? $_POST['ChangeFichier'] : 0;
$Type           = isset($_POST['Type']) ? $_POST['Type'] : 'com';



if ($AncienBlog == 'http://.'.$Domaine)
    die('ERREUR : vous devez entrer le nom de votre blog.');


if (substr($NouveauBlog, -1) == '/')
    $NouveauBlog = substr($NouveauBlog, 0, -1);


$FichierXML = 'xml/' . str_replace(array('http://', '/'), '', $AncienBlog) . '_' . date('d-m-Y') . '_' . $FichierNum . '.xml';


$doc = new DomDocument();
@$doc->loadHTMLFile($AncienBlog.'/'.$Page.'/');
//$msn = file_get_contents($AncienBlog.'/'.$Page.'/');
//$doc->loadHTML($msn);
$finder = new DomXPath($doc);       // Pour la recherche par CLASS


$NodesTitres = $finder->query("//*[contains(@class, 'article-title-h2')]");  // Le lien de l'article
$NbArticles  = $NodesTitres->length;

if ($NbArticles==0 and $Page==1 and $NumArt==0)
    die('ERREUR : le blog <b>'.$AncienBlog.'</b> n\'a pas été trouvé.');


echo '&bull; Page lue : <b>' . $Page . '</b><br>';


if ($NumArt < $NbArticles){
    
    if (($Page == 1 and $NumArt == 0 and $NumCom == 1) or $ChangeFichier == 1){
        
        // Les rubriques (categories) :
        $Rubriques = array();
        $IsRubriques = $doc->getElementById('rubriques');     
        if (!$IsRubriques)
            echo 'ERREUR : Les rubriques ne sont pas affichées sur votre blog et ne seront pas récupérées.<br>';
        else{
            $NodesRubr = $doc->getElementById('rubriques')->getElementsByTagName('a');
            foreach ($NodesRubr as $key => $value) {
                list(, , $TagRubr) = explode('/', $value->getAttribute('href'));
                $Rubriques[] = $TagRubr;
            }
        }
        
        // Debut du fichier XML
        $XML = '<?xml version="1.0" encoding="UTF-8" ?>
                <!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
                <!-- It contains information about your site\'s posts, pages, comments, categories, and other content. -->
                <!-- You may use this file to transfer that content from one site to another. -->
                <!-- This file is not intended to serve as a complete backup of your site. -->

                <!-- To import this information into a WordPress site follow these steps: -->
                <!-- 1. Log in to that site as an administrator. -->
                <!-- 2. Go to Tools: Import in the WordPress admin panel. -->
                <!-- 3. Install the "WordPress" importer from the list. -->
                <!-- 4. Activate & Run Importer. -->
                <!-- 5. Upload this file using the form provided on that page. -->
                <!-- 6. You will first be asked to map the authors in this export file to users -->
                <!--    on the site. For each author, you may choose to map to an -->
                <!--    existing user on the site or to create a new user. -->
                <!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
                <!--    contained in this file into your site. -->

                <!-- generator="WordPress/3.8" created="'.date('Y-m-d H:i').'" -->
                <rss version="2.0"
                        xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
                        xmlns:content="http://purl.org/rss/1.0/modules/content/"
                        xmlns:wfw="http://wellformedweb.org/CommentAPI/"
                        xmlns:dc="http://purl.org/dc/elements/1.1/"
                        xmlns:wp="http://wordpress.org/export/1.2/"
                >

                <channel>
                    <title>'.$AncienBlog.'</title>
                    <link>'.$AncienBlog.'</link>
                    <description>Recuperation de '.$AncienBlog.'</description>
                    <pubDate>'.date('D, d M Y H:i:s O').'</pubDate>
                    <language>fr-FR</language>
                    <wp:wxr_version>1.2</wp:wxr_version>
                    <wp:base_site_url>'.$NouveauBlog.'</wp:base_site_url>
                    <wp:base_blog_url>'.$NouveauBlog.'</wp:base_blog_url>

                    <wp:author><wp:author_id>1</wp:author_id><wp:author_login>'.$VotreNom.'</wp:author_login><wp:author_email>'.$VotreEmail.'</wp:author_email><wp:author_display_name><![CDATA['.$VotreNom.']]></wp:author_display_name><wp:author_first_name><![CDATA[]]></wp:author_first_name><wp:author_last_name><![CDATA[]]></wp:author_last_name></wp:author>
        ';
        
        // Les rubriques
        if ($IsRubriques)
            foreach ($Rubriques as $IdRubr=>$NomRubr)
                $XML.= '
                        <wp:category><wp:term_id>'.$IdRubr.'</wp:term_id><wp:category_nicename>'.$NomRubr.'</wp:category_nicename><wp:category_parent></wp:category_parent><wp:cat_name><![CDATA['.$NomRubr.']]></wp:cat_name></wp:category>';
            
        
        $XML.= '    <wp:category><wp:term_id>1</wp:term_id><wp:category_nicename>non-classe</wp:category_nicename><wp:category_parent></wp:category_parent><wp:cat_name><![CDATA[Non classé]]></wp:cat_name></wp:category>

                    <generator>http://wordpress.org/?v=3.8</generator>';   
    
        @unlink($FichierXML);

        // Crée le fichier xml
        $FileXML = fopen($FichierXML, 'w');
        fwrite($FileXML, $XML);
        fclose($FileXML);    
    }
 
    
    $LienArt = $NodesTitres->item($NumArt)->getElementsByTagName('a')->item(0)->getAttribute('href');
    $CheminArticle = $AncienBlog . $LienArt . $NumCom . '/'; // Exemple http://magicmanu.bricoblog.fr/248037/Fabriquer-un-abri-bois-Bucher/3/
    
    echo '&bull; Article : <b>' . $LienArt . '</b> (' . ($NumArt + 1) . '/' . $NbArticles . ')<br>';
    echo '&bull; Page commentaire : <b>' . $NumCom . '</b><br>';
    echo '&bull; Nombre de fichiers XML : <b>' . $FichierNum . '</b><br>';
    ?>
    <iframe Name="FrmArt" width="100%" height="200" frameborder="0"></iframe>
    <form method="post" action="TraitementArticle.php" name="FormArt" target="FrmArt">
        <input type="hidden" name="Lien" value="<?php echo $CheminArticle; ?>">
        <input type="hidden" name="Page" value="<?php echo $Page; ?>">
        <input type="hidden" name="NumArt" value="<?php echo $NumArt; ?>">
        <input type="hidden" name="NumCom" value="<?php echo $NumCom; ?>">
        <input type="hidden" name="AncienBlog" value="<?php echo $AncienBlog; ?>">
        <input type="hidden" name="NouveauBlog" value="<?php echo $NouveauBlog; ?>">
        <input type="hidden" name="VotreNom" value="<?php echo $VotreNom; ?>">
        <input type="hidden" name="FichierXML" value="<?php echo $FichierXML; ?>">
        <input type="hidden" name="FichierNum" value="<?php echo $FichierNum; ?>">
        <input type="hidden" name="Type" value="<?php echo $Type; ?>">
    </form>
    <script type="text/javascript">
        setTimeout("FormArt.submit()", 500);
    </script>
    <?php
}

// Fin du fichier
else{
    $XML = '
            </channel>
        </rss>';
    $FileXML = fopen($FichierXML, 'a');
    fwrite($FileXML, $XML);
    fclose($FileXML);       
    
    echo 'Traitement terminé !<br><br>';
    
    if ($FichierNum>1)
        echo $FichierNum . ' fichiers de moins de 2Mo générés :<br><br>';
    
    for ($i = 1; $i <= $FichierNum; $i++){
        $PosUnd = strrpos($FichierXML, '_');
        $LienFichier = substr($FichierXML, 0, $PosUnd) . '_' . $i . '.xml';
        echo '<a href="'.$LienFichier.'" target="_blank">'.str_replace('xml/', '', $LienFichier).'</a><br>';
    }
    echo '<i>Clic-droit : Enregistrer le lien (ou la cible du lien) sous...</i>';
}
